TP2: Premier réseau de neurone avec PyTorch
=============

Introduction au sujet
-----

L'objectif de ce sujet est de mettre en place un premier réseau de neurone pour classer des fleurs de la base IRIS.

Le code est à écrire en python3 à la suite des questions dans ce fichier. Vous appuierez soit sur le bouton *run cell*, soit sur les touches *Ctrl-Entrée*, à l’intérieur de la zone de saisie, pour lancer l'exécution de vos commandes. Si la commande est en cours d’exécution une étoile apparaît à côté de la zone de saisie de la commande : In [\*]. Une fois le calcul achevé, l'étoile est remplacée par le numéro du run permettant de retrouver par la suite dans quel ordre ont été lancés chaque bloc.

N'hésitez pas à regarder régulièrement la documentation de ces librairies, des exemples d'utilisation accompagnent généralement l'explication de chaque fonction.

Langage utilisé:
- Python 3: https://docs.python.org/3/

Librairie de math:
- Numpy: https://docs.scipy.org/doc/numpy/reference/
- Scipy: https://docs.scipy.org/doc/scipy/reference/

Librairie d'affichage de données:
- Matplotilb: https://matplotlib.org/contents.html

Librairie Pytorch:
- PyTorch: https: https://pytorch.org/docs/stable/

Commencez par importer les librairies nécessaires au TP.

In [1]:
# Import Torch
import torch
import torch.nn as nn
from torch.utils.tensorboard import SummaryWriter

# Import numpy et matplotlib
import numpy as np
import matplotlib.pyplot as plt

# Import de scikit-learn
import sklearn as sk
import sklearn.datasets
import sklearn.model_selection

%matplotlib inline

PyTorch: Premier réseau sur la base IRIS
-----

Nous allons dans ce TP étudier la base *IRIS* et tester un réseau entièrement connecté dessus. 

Commencez par charger la base *IRIS* avec sckit-learn. Vous mettrez les descripteurs des fleurs dans une variable `X` et les labels dans une variable `y`.

Vérifiez que le code suivant affiche bien des *True*.

In [3]:
print(X.shape == (150,4))
print(y.shape == (150,))

True
True


Séparez l'ensemble d'apprentissage en deux en utilisant la fonction train_test_split de sckit-learn. Un ensemble d'apprentissage *train* et un ensemble de *test*. Vous prendrez 1/3 des images pour le test.

Vérifiez les dimensions des données produites:

In [5]:
print(2*len(X)/3,'->',train.shape,y_train.shape)
print(len(X)/3,'->',test.shape,y_test.shape)

100.0 -> (100, 4) (100,)
50.0 -> (50, 4) (50,)


Définissez un classifieur *iris_classifier* correspondant à un réseau entièrement connecté de 3 couches cachées de tailles [10,20,10]. Après chaque couche cachée, vous appliquerez une fonction d'activation de type ReLU. N'oubliez pas la dernière couche de sortie. Vous utiliseriez `torch.nn.Sequential` pour faire cette question.

Définissez un objet `iter_train` permettant de parcourir la base de donnée d'entrainement avec des batchs aléatoires de taille 32. Vous utiliserez les classes `TensorDataset` et `DataLoader` pour cette question.

Définissez un objet `iter_test` permettant de parcourir la base de donnée de test avec des batchs de taille 10 concervant l'ordre d'origine des exemples.

Définissez une optimiser de type gradient stochastique initialisé avec un taux d'apprentissage de $10^{-2}$.

Définissze un critère de type cross-entropie qui sera utilisé comme fonction de coût optimisant notre réseau.

Effectuez 100 époques d'apprentissage du classifieur `iris_classifier` avec les données de `iter_train`. Vous utiliserez pour celà un algorithme de gradient stochastique avec une fonction de coût de type cross-entropie.

0 /100, loss= 0.8554646968841553
10 /100, loss= 1.0755116939544678
20 /100, loss= 1.0671064853668213
30 /100, loss= 0.9227153658866882
40 /100, loss= 0.9295974969863892
50 /100, loss= 0.5762283802032471
60 /100, loss= 0.479737788438797
70 /100, loss= 0.6177878379821777
80 /100, loss= 0.33995407819747925
90 /100, loss= 0.4962453544139862
99 /100, loss= 0.3136560320854187


Evaluez les performances du réseau appris à la  question précédente sur les données de test de `iter_test`. Pour faire  cette  question vous calculerez dans une boucle le nombre de fois que l'algorithme s'est trompé sur la base de test. Pensez à désactiver le calcul des gradients sur la base de test afin de pas perturbé avec des données de tests de nouveaux apprentissages de votre réseau.

Accuracy sur test: 78.0%


Relancez les lignes effectuant l'apprentissage et l'évaluation. Comment évolue les performances d'apprentissage ? 

Utilisez tensorboard pour visualiser le graphe correspondant à votre réseau et les différentes courbes correspondant à l'apprentissage de ce dernier.

Vous pouvez pour cela:
- Soit installez le plugin tensorboard pour jupyter: pip3 install --user jupyter-tensorboard

Puis vous suivez les informations d'écrit sur la page: https://github.com/lspvic/jupyter_tensorboard
- Soit lancer dans un terminal: tensorboard --logdir=.

Puis vous vous connectez à http://localhost:6006

PyTorch: Définition d'un réseau couche par couche
-----

Nous allons dans cette partie redéfinir le réseau couche par couche.

Définissez une classe `Net` définissant le réseau précédant sans utiliser de `torch.nn.Sequential`. 

Apprenez ce réseau sur les données d'apprentissage de la base IRIS avec un algorithme de descende de gradient de type AdaGrad dont le taux d'apprentissage est de $10^{-2}$ avec une fonction de coût de type cross-entropie.

0 /200, loss= 1.1917170286178589
100 /200, loss= 0.3672744035720825
200/200, loss= 0.13490986824035645


Testez le réseau que vous venez d'apprendre sur la base de test.

Accuracy sur test: 96.0%


Sauvegardez le modèle que vous venez d'apprendre dans un fichier.

Chargez le réseau que vous venez de sauvegarder et vérifier que les performances sur la base de test n'ont pas changé.

Accuracy sur test: 96.0%


Comparez les graphes des deux méthodes dans tensorboard. Retrouvez-vous les même éléments ? Qu'est ce qui diffère entre les deux versions ? 

Comparaison avec un SVM 
----

En utilisant la librairie sckit-learn et le cours de Machine learning du premier semestre, trouver les performances du meilleur SVM sur ces données et comparer les performances avec celle du réseau de neurone.

In [20]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
from sklearn.metrics import *



0.98
              precision    recall  f1-score   support

           0     1.0000    1.0000    1.0000        16
           1     1.0000    0.9474    0.9730        19
           2     0.9375    1.0000    0.9677        15

   micro avg     0.9800    0.9800    0.9800        50
   macro avg     0.9792    0.9825    0.9802        50
weighted avg     0.9812    0.9800    0.9801        50

[[16  0  0]
 [ 0 18  1]
 [ 0  0 15]] 0.8 0.74


/home/lechervy/.local/lib/python3.6/site-packages/sklearn/model_selection/_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)
